name: Forkzilion Workflow

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main
       - name: gitcloning
         run: |
           git clone -b pruhsuperlight https://github.com/DunggVN/Forkzilion-Creds
